name:                api-mailchimp
version:             0.1.0.0
github:              "sigrlami/api-mailchimp"
license:             BSD3
author:              "Sergey Bushnyak"
maintainer:          "sergey.bushnyak@sigrlami.eu"
copyright:           "(c) 2020, Sergey Bushnyak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sigrlami/api-mailchimp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  api-mailchimp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-mailchimp

tests:
  api-mailchimp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-mailchimp
